server:
  port: 9001

spring:
  application:
    name: PRODUCT-SERVICE
  zipkin:
    base-url:http://127.0.0.1:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



